///<auto-generated />
namespace Bookify.Domain.Abstractions
{
    public abstract class Entity(Guid id) 
    {
        private readonly List<IDomainEvent> _domainEvents = [];
        public Guid Id { get; init; } = id;
        public bool IsDeleted { get; private set; }
        public void Delete() => IsDeleted = true;
        public IReadOnlyCollection<IDomainEvent> GetDomainEvents => _domainEvents.AsReadOnly();
        public void RaiseDomainEvent(IDomainEvent domainEvent)=>_domainEvents.Add(domainEvent);
        public void ClearDomainEvents()=>_domainEvents.Clear();
    }

    public record Error(string Code, string Message)
    {
        public static Error NoError => new("Error.NoError", "this is Sucess Result that have no Error");
        public static Error NullError => new("Error.NullValue", "Null Value was Provided");
    }



    public record Result<T>(T Value, Error? Error = null)
    {
        public bool IsSuccess => Value is not null && (Error == null || Error == Error.NoError);
        public bool IsFaliure => !IsSuccess;
        public static Result<T> Success(T value) => new (value, Error.NoError);
        public static Result<T> Failure(Error error) => new(default!, error);

        public static implicit operator Result<T>(T value) => value is not null ? Success(value) : Failure(Error.NullError);
    }
}
